import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import adminRouter from "./admin.js";
import teacherRouter from "./teacher.js";
import studentRouter from "./student.js";
import roomsRouter from "./rooms.js";
import schedulesRouter from "./schedules.js";
import teacherAssignmentsRouter from "./teacher_assignments.js";
import blockedDatesRouter from "./blocked_dates.js";
import notificationsRouter from "./notifications.js";
import scolariteRouter from "./scolarite.js";
import honorairesRouter from "./honoraires.js";
import attendanceRouter from "./attendance.js";
import messagesRouter from "./messages.js";
import housingRouter from "./housing.js";
import pushRouter from "./push.js";
import devRouter from "./dev.js";
import specialJuryRouter from "./special_jury.js";
import studentCardsRouter from "./student-cards.js";
import publicRouter from "./public.js";
import evaluationsRouter from "./evaluations.js";
import parentRouter from "./parent.js";
import webauthnRouter from "./webauthn.js";
import reclamationsRouter from "./reclamations.js";
import bibliothequeRouter from "./bibliotheque.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/dev", devRouter);
router.use("/admin", adminRouter);
router.use("/admin/rooms", roomsRouter);
router.use("/admin/schedules", schedulesRouter);
router.use("/admin/teacher-assignments", teacherAssignmentsRouter);
router.use("/admin/blocked-dates", blockedDatesRouter);
router.use("/teacher", teacherRouter);
router.use("/student", studentRouter);
router.use("/notifications", notificationsRouter);
router.use("/scolarite", scolariteRouter);
router.use("/honoraires", honorairesRouter);
router.use(attendanceRouter);
router.use(messagesRouter);
router.use(housingRouter);
router.use("/push", pushRouter);
router.use("/admin", specialJuryRouter);
router.use(studentCardsRouter);
router.use(publicRouter);
router.use(evaluationsRouter);
router.use(parentRouter);
router.use("/auth", webauthnRouter);
router.use(reclamationsRouter);
router.use(bibliothequeRouter);

export default router;
